"""Contracts every module of the sorting line implements. FROZEN: owned by the integrator.

Propose a change by appending to ~/robotics/INTEGRATOR.md; do not edit this file in place. Everything
else in `line/` codes against these types, so the control panel, the closed loop and the self-tests keep
working when a stub is swapped for the real implementation.

Data flow of the physical line (coffee bean chute, see BUILD_ASBUILT.md):

    FrameSource.grab() ─▶ BeanDetector.detect() ─▶ BeanClassifier.classify() ─▶ GateDriver.pulse()
        (iPhone)             (dark blob on paper)      (rule / sklearn / …)        (SG90 on D9 via ArduinoLink)

Units: pixels for image coordinates (u right, v down), millimetres for physical sizes, seconds for time
(`time.monotonic()`), servo angles in degrees 0-180 exactly as the magnet_arm firmware takes them.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Protocol, runtime_checkable

import numpy as np


def now() -> float:
    return time.monotonic()


# ------------------------------------------------------------------ common
@dataclass
class Check:
    """One self-test result. `detail` is human text shown in the panel; keep it to one line."""

    name: str
    ok: bool
    detail: str = ""
    ms: float = 0.0


@runtime_checkable
class Module(Protocol):
    """Every subsystem exposes these three so the panel can show health and run self-tests generically."""

    name: str

    def status(self) -> dict:
        """JSON-serialisable snapshot (numbers, strings, bools, lists). Must never raise and must return fast (<50 ms)."""
        ...

    def selftest(self) -> list[Check]:
        """Exercise the module without moving anything dangerous. May take a few seconds. Never raises: failures are Checks with ok=False."""
        ...

    def close(self) -> None: ...


# ------------------------------------------------------------------ arduino / motors
@dataclass
class ArduinoState:
    pos: tuple[int, int, int] | None  # (base, shoulder, elbow) degrees as reported by `?`
    magnet: bool
    moving: bool
    belt: int  # last commanded conveyor speed -100..100 (the firmware does not report it)
    raw: str  # the raw `?` reply
    port: str
    ok: bool = True
    error: str = ""


class ArduinoLink(Module, Protocol):
    """One line of the magnet_arm serial protocol in, one reply out. Thread-safe. Reconnects on ENXIO.

    Implementations (line/arduino_link.py, owner: arduino agent):
      DirectSerial(port)      pyserial, holds the port open, waits for boot, `C 0` on connect and close
      HttpPanelLink(url)      proxies to the running conveyor_button.py (POST /cmd?line=…) so two programs never fight for the port
      FakeArduino()           firmware emulation in Python (ramps, `?` reply, belt) for tests and the panel without hardware
    """

    def cmd(self, line: str) -> str: ...

    def query(self) -> ArduinoState: ...


class GateDriver(Module, Protocol):
    """The swing door. `flush` = wall in line, `open` = 25° into the channel (see config gate.flush_deg / open_deg).

    Implementation (line/gate.py, owner: arduino agent): `Gate(link, cfg)`. `pulse` is NON-blocking: it schedules
    open at now+delay_s and flush at now+delay_s+dwell_s on a timer thread, coalescing overlapping pulses (a second
    suspect while the door is open just extends the dwell). `state` is 'flush' | 'scheduled' | 'open'.
    """

    state: str

    def flush(self) -> None: ...

    def open(self) -> None: ...

    def pulse(self, delay_s: float, dwell_s: float) -> None: ...


# ------------------------------------------------------------------ cameras
@dataclass
class Frame:
    bgr: np.ndarray  # HxWx3 uint8, BGR (OpenCV order)
    t: float  # monotonic capture time
    seq: int  # increments per captured frame
    source: str  # camera name


class FrameSource(Module, Protocol):
    """Latest-frame camera. `grab` returns the newest frame and never blocks longer than one frame period.

    Implementations (line/camera_source.py, owner: camera agent):
      RealCamera(match='iphone', width, height)   AVFoundation via OpenCV, resolved BY NAME (never by index), background reader thread
      FileCamera(paths, fps)                       replays images/video for tests and offline classifier work
      SyntheticCamera(...)                         draws beans rolling on white paper (deterministic, for pipeline tests)
    `status()` must include: name, resolution, fps_measured, grab_latency_ms, frames, dropped.
    """

    def grab(self) -> Frame: ...


@dataclass
class ROI:
    """Inspection zone in pixels (the 9–15 cm stretch of the chute). Inclusive-exclusive like numpy slices."""

    x0: int
    y0: int
    x1: int
    y1: int

    def crop(self, bgr: np.ndarray) -> np.ndarray:
        return bgr[self.y0 : self.y1, self.x0 : self.x1]

    @property
    def w(self) -> int:
        return self.x1 - self.x0

    @property
    def h(self) -> int:
        return self.y1 - self.y0


# ------------------------------------------------------------------ vision
@dataclass
class Blob:
    """One candidate bean in a frame. Pixel coordinates are in the FULL frame, not the ROI."""

    u: float  # centroid column
    v: float  # centroid row
    bbox: tuple[int, int, int, int]  # x, y, w, h in px
    area_px: float
    partial: bool  # touches the ROI border → not fully visible, do not classify yet
    features: dict[str, float] = field(default_factory=dict)  # detector-specific measurements (see bean_vision.FEATURES)


class BeanDetector(Module, Protocol):
    """Dark objects on the white paper floor → blobs with features.

    Implementation (line/bean_vision.py, owner: camera agent): `PaperBeanDetector(cfg)`. Must run in < 15 ms on a
    1280×720 frame with a 300×200 ROI. Publishes `FEATURES: list[str]` (the keys every blob carries, same names as
    coffee_sorter/vision.py where the meaning is the same: area_mm2, major_mm, minor_mm, aspect, fill, solidity,
    mean_r/g/b, mean_gray, std_gray, mean_h/s/v, dark_frac, n_dark_spots, …). mm scale comes from cfg.camera.px_per_mm.
    """

    def detect(self, frame: Frame, roi: ROI | None = None) -> list[Blob]: ...


# ------------------------------------------------------------------ classification
@dataclass
class Verdict:
    label: str  # 'good' or a defect/foreign class name; 'unknown' when unsure
    p_defect: float  # 0..1
    suspect: bool  # the decision the gate acts on
    reason: str  # one line a human can read in the panel
    ms: float  # inference time
    classifier: str  # implementation name


class BeanClassifier(Module, Protocol):
    """One blob in, one verdict out. Budget: the whole photo→door path has ~0.45 s, so aim for < 30 ms.

    Implementations (line/classifier.py, owner: coffee-sim agent):
      RuleClassifier(cfg)        thresholds on the blob features (colour, size, dark spots); tunable from the panel, saved in config.json
      SklearnClassifier(path)    coffee_sorter Model (HistGradientBoosting + Mahalanobis anomaly) over the same FEATURES
    `status()` includes: name, classes, thresholds/model path, n_classified, mean_ms.
    """

    def classify(self, frame: Frame, blob: Blob) -> Verdict: ...


# ------------------------------------------------------------------ closed loop
@dataclass
class LineEvent:
    t: float
    kind: str  # 'bean_seen' | 'verdict' | 'gate_open' | 'gate_flush' | 'bean_lost' | 'error' | 'note'
    data: dict = field(default_factory=dict)


@dataclass
class Sample:
    """A labelled crop saved by the panel for training / evaluation: datasets/beans/<label>/<ts>.png + .json"""

    path: str
    label: str
    features: dict[str, float]
    verdict: Verdict | None
    t: float
